config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("api/", include("home.api.urls")),
    path("api/", include("forum.api.urls")),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/api/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("hello/", views.hello_world, name="hello_world"),
    path("list/", views.ArticleListView.as_view()),
    path("<slug:slug>/", views.ArticleView.as_view()),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("add/", views.ArticleAddView.as_view(), name="article-add"),
    path("list/", views.ArticleListView.as_view(), name="article-list"),
    path("<slug:slug>/", views.ArticleView.as_view()),
    path("<slug:slug>/new-thread/", views.ArticleView.as_view()),
    path("<slug:slug>/<str:thread>/", views.ArticleThreadView.as_view()),
    path("<slug:slug>/<str:thread>/<int:pid>/", views.ArticleThreadView.as_view()),
]

home/models.py
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from djongo import models as djongo_models

from users.models import CustomUser


class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        ordering = ["name"]

    def save(self, *args, **kwargs):
        self.name = re.sub(r"[^a-zA-Z0-9]", "", self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f"#{self.name}"


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Content(djongo_models.Model):
    slug = djongo_models.SlugField(max_length=50, blank=True, unique=True, primary_key=True)
    title = djongo_models.CharField(max_length=200)
    text = djongo_models.TextField()
    published = djongo_models.BooleanField(default=False)

    class Meta:
        ordering = ["title"]

    def save(self, *args, **kwargs):
        if not self.slug:
            pl_chars = dict(
                zip(
                    ("ą", "ć", "ę", "ł", "ń", "ó", "ś", "ż", "ź"),
                    ("a", "c", "e", "l", "n", "o", "s", "z", "z"),
                )
            )
            title = "".join(
                [
                    pl_chars[_] if _ in pl_chars else _
                    for _ in self.title.split(".")[0].lower() or self.title.lower()
                ]
            )
            if not (slug := slugify(title)):
                raise ValidationError("Slug created from title is empty.")
            self.slug = slug
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.slug


class Article(models.Model):
    slug = models.OneToOneField(Content, max_length=50, on_delete=models.CASCADE, primary_key=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def save(self, *args, **kwargs):
        res = super().save(*args, **kwargs)
        if res is None:
            content = Content.objects.get(slug=self.slug)
            content.published = True
            content.save()
        return res

    def __str__(self):
        return str(self.slug)

home/api/views.py
from django.http import JsonResponse
from rest_framework import generics

from home.api.serializers import ArticleSerializer
from home.models import Article


def hello_world(request):
    return JsonResponse(data={"message": "Hello World!"})


class ArticleView(generics.RetrieveAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    lookup_field = "slug"


class ArticleListView(generics.ListAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    lookup_field = "slug"

home/views.py
import re

import markdown
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import TemplateView, DetailView, ListView, FormView

from forum.forms import StartNewThreadForm, AddNewPostForm
from forum.models import Post, Thread
from home.models import Article, Content, Tag, Category
from users.models import CustomUser


class HomeView(TemplateView):
    template_name = "home/home.html"


class ArticleView(DetailView, FormView):
    model = Article
    template_name = "home/article.html"
    form_class = StartNewThreadForm
    content = threads = thread = posts = back = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not re.match(r".*/new-thread/$", self.request.path):
            context["threads"] = self.threads
        context["content"] = self.content
        context["thread"] = self.thread
        context["posts"] = self.posts
        context["slug"] = self.object.slug
        return context

    def get_queryset(self):
        self.content = get_object_or_404(Content, slug=self.kwargs["slug"])
        self.content.text = markdown.markdown(self.content.text)
        if thread := self.kwargs.get("thread"):
            self.thread = Thread.objects.filter(id=thread).first()
            self.posts = Post.objects.filter(thread_id=self.thread)
        else:
            self.threads = Thread.objects.filter(slug=self.kwargs["slug"])
        return Article.objects.filter(slug=self.content, is_active=True)

    def form_valid(self, form):
        slug = self.model.objects.filter(slug=self.kwargs["slug"]).first()
        user = CustomUser.objects.filter(name=self.request.user).first()
        thread = form.new_thread_form.save(slug=slug, user=user)
        form.new_post_form.save(thread=thread, user=user)
        return redirect(f"/{slug}/{thread.id}/")


class ArticleThreadView(ArticleView):
    template_name = "home/article.html"
    form_class = AddNewPostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if pid := self.kwargs.get("pid"):
            context["pid"] = pid
            p = Post.objects.get(thread_id=self.thread.id, id=pid)
            context["form"].fields["text"].initial = p.text
            context["action"] = "Show" if p.hidden else "Hide"

        return context

    def form_valid(self, form):
        user = CustomUser.objects.filter(name=self.request.user).first()
        thread = Thread.objects.filter(id=self.kwargs["thread"]).first()

        if pid := self.kwargs.get("pid"):
            if p := Post.objects.filter(id=pid).first():
                match self.request.POST.get("submit").split()[0].lower():
                    case "delete":
                        p.delete()
                    case "hide" | "show":
                        p.hidden = not p.hidden
                        p.save()
                    case _:
                        p.text = self.request.POST["text"]
                        p.save()
        else:
            form.new_post_form.save(thread=thread, user=user)

        return redirect(f"/{self.kwargs['slug']}/{thread.id}/")


class ArticleListView(ListView):
    model = Article
    template_name = "home/article-list.html"
    ctx = {
        "authors": {},
        "order_fields": {"Date": "published", "Title": "slug__title"},
        # default values for form fields
        "author_id": 0,
        "date_from": "",
        "date_to": "",
        "order_by": "Date",
        "direction": "desc",
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.ctx)
        return context

    def get_queryset(self):
        self.ctx.update({key: value for key, value in self.request.POST.items() if key != "csrfmiddlewaretoken"})
        field = self.ctx["order_fields"][self.ctx["order_by"]]
        articles = Article.objects.filter(is_active=True).order_by("-" * (self.ctx["direction"] == "desc") + field)
        self.ctx["authors"] = dict(articles.values_list("author_id", "author__name").distinct())

        if self.ctx["date_from"]:
            articles = articles.filter(published__gte=self.ctx["date_from"])
        if self.ctx["date_to"]:
            articles = articles.filter(published__lte=f'{self.ctx["date_to"]} 23:59')
        if i := int(self.ctx["author_id"] or 0):
            articles = articles.filter(author=i)

        return articles.values_list("slug", "slug__title", "author_id")


class ArticleAddView(View):
    keys = ("err", "title", "slug", "tags", "selected_categories", "text_file")

    def get(self, request):
        ctx = {key: "" for key in self.keys}
        ctx["categories"] = Category.objects.all()
        return render(request, "home/article-add.html", context=ctx)

    def post(self, request):
        ctx = {key: request.POST.get(key) for key in self.keys[:-2]}
        ctx["selected_categories"] = list(map(int, request.POST.getlist("selected_categories")))
        text = f.read().decode("UTF-8") if (f := request.FILES.get("text_file")) else ""
        ctx["err"] = list()

        if not ctx["title"]:
            ctx["err"].append("Title cannot be empty.")
        if not text:
            ctx["err"].append("Choose a file.")
        if ctx["slug"] and re.search(r"[^a-z-\d]", ctx["slug"]):
            ctx["err"].append("Use only lower case letters, digits and '-' for slug")
        if tags := (ctx["tags"] or "").split():
            if wrong_tags := [tag for tag in tags if not re.match(r"#[^\W_]+$", tag)]:
                ctx["err"].append("Wrong tags: " + ", ".join(wrong_tags))
                ctx["err"].append("Tags should start with # and contains alphanumeric chars only")
        if ctx["err"]:
            ctx["categories"] = Category.objects.all()
            return render(request, "home/article-add.html", context=ctx)

        tag_objs = [
            _id if (_id := Tag.objects.filter(name=tag[1:]).first()) else Tag.objects.create(name=tag[1:])
            for tag in tags
        ]
        content = Content.objects.create(slug=ctx["slug"], title=ctx["title"], text=text)
        article = Article.objects.create(slug=content, author=request.user)
        article.tags.set(tag_objs)
        article.categories.set(ctx["selected_categories"])

        return redirect(f"/{article.slug}/")

home/templates/home/article-add.html
{% extends "base.html" %}

{% block title %}Add new article{{ content.title }}{% endblock %}

{% block  content %}
    <form class="px-3 py-2" method="post" action="#" id="form-add" style="background-color: #f5f5f5" enctype="multipart/form-data">
        {% csrf_token %}
        <label class="control-label"><strong>Content</strong></label>
        <div class="row">
            <div class="col-12">
                <label class="m-2 control-label" for="title">Title: </label>
                <div class="col">
                </div>
                <input class="mx-2 form-control-sm w-75" type="text" name="title" id="title" value="{{ title }}"
                       maxlength="200">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <label class="m-2 control-label" for="slug">Slug: </label>
                <div class="col">
                </div>
                <input class="mx-2 form-control-sm w-50" type="text" name="slug" id="slug" value="{{ slug }}"
                       maxlength="50">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <label class="m-2 control-label" for="text_file">File: </label>
                <div class="col">
                </div>
                <input class="mx-2 form-control-sm w-75" type="file" name="text_file" id="text_file"
                       value="{{ text_file }}" accept=".txt">
            </div>
        </div>

        <label class="control-label mt-2 pt-3"><strong>Article</strong></label>
        <div class="row">
            <div class="col-12">
                <label class="m-2 control-label" for="tags">Tags: </label>
                <div class="col">
                </div>
                <input class="mx-2 form-control-sm w-75" type="text" name="tags" id="tags" value="{{ tags }}"
                       maxlength="200" placeholder="space separated tags">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <label class="m-2 control-label" for="categories">Categories: </label>
                <div class="col">
                </div>
                <select class="mx-2 form-control-sm w-75" name="selected_categories" id="categories" multiple>
                    {% for category in categories %}
                        <option value="{{ category.id }}"{% if category.id in selected_categories %}
                                selected{% endif %}>{{ category }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <button class="mx-2 my-2 form-control-sm" type="submit">Publish</button>
            </div>
        </div>
    </form>
    {% if err %}
        <div class="alert alert-warning" role="alert">
        {% for msg in err %}
            {{ msg }}<br>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

home/templates/home/article-list.html
{% extends "base.html" %}

{% load static %}
{% load filters %}

{% block title %}List of articles{% endblock %}

{% block  content %}

    <form class="form-horizontal px-3 py-2" method="post" action="#" id="form-list" style="background-color: #f5f5f5">
        {% csrf_token %}
        <label class="control-label" for="form-filter">Filter by:</label>
        <div class="form-group" id="form-filter">
            <label class="m-2 control-label" for="select-author">Author</label>
            <select class="form-horizontal m-2" id="select-author" name="author_id">
                <option value="">All</option>
                {% for id, author in authors.items %}
                    <option value="{{ id }}"{% if id == author_id %} selected{% endif %}>{{ author }}</option>
                {% endfor %}
            </select>
            <label class="m-2 control-label" for="date-from">Date from</label>
            <input type="date" id="date-from" name="date_from" value="{{ date_from }}">
            <label class="m-2 control-label" for="date-to">Date to</label>
            <input type="date" id="date-to" name="date_to" value="{{ date_to }}">
        </div>
        <label class="control-label" for="form-order">Order by:</label>
        <div class="form-group" id="form-order">
            <label class="m-2 control-label" for="select-order">Field name</label>
            <select class="form-horizontal m-2" id="select-order" name="order_by">
                {% for key in order_fields.keys %}
                    <option value="{{ key }}"{% if order_by == key %} selected{% endif %}>{{ key }}</option>
                {% endfor %}
            </select>
            <label class="m-2 control-label" for="asc">ASC</label>
            <input type="radio" name="direction" value="asc" id="asc"{% if direction == "asc" %} checked{% endif %}>
            <label class="m-2 control-label" for="desc">DESC</label>
            <input type="radio" name="direction" value="desc" id="desc"{% if direction == "desc" %} checked{% endif %}>
            <button type="submit" class="button px-2 mx-3">Show</button>
        </div>
    </form>

    <div class="list-group">
        {% for slug, title, author_id in article_list %}
            <a class="list-group-item border-0" href="/{{ slug }}/">
                <img class="mx-lg-3" src="{% static 'images/link_black_24dp.svg' %}" alt="Go to article">
                {{ title }}
                <button class="badge bg-secondary mx-lg-3" form="form-filter" name="author_id"
                        value="{{ author_id }}">{{ authors|get_item:author_id }}</button>
            </a>
        {% endfor %}
    </div>

{% endblock %}

home/templates/home/article.html
{% extends "base.html" %}

{% block title %}{{ content.title }}{% endblock %}

{% block  content %}
    <div>{{ content.text|safe }}</div>
{% endblock %}

{% block forum %}
    {% if user.is_authenticated %}
        <hr style="border: 1px solid indianred; width: 100%;"/>
        {% if thread %}
            {% include "forum/thread.html" %}
        {% else %}
            {% if threads %}
                {% include "forum/main.html" %}
            {% else %}
                {% include "forum/new_thread.html" %}
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}

home/templates/home/home.html
{% extends "base.html" %}

{% block  content %}
    <h1>Home</h1>
{% endblock %}