config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("api/", include("home.api.urls")),
    path("api/", include("forum.api.urls")),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("add/", views.ArticleAddView.as_view(), name="article-add"),
    path("list/", views.ArticleListView.as_view(), name="article-list"),
    path("<slug:slug>/", views.ArticleView.as_view()),
    path("<slug:slug>/new-thread/", views.ArticleView.as_view()),
    path("<slug:slug>/<str:thread>/", views.ArticleThreadView.as_view()),
    path("<slug:slug>/<str:thread>/<int:pid>/", views.ArticleThreadView.as_view()),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path("register/", views.SendRegistrationLinkView.as_view(), name="registration"),
    path("link-sent/", views.SendRegistrationLinkView.as_view(), name="link-sent"),
    path("register/<uuid>/", views.RegisterUserView.as_view(), name="register-uuid"),
]

templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary bg-primary" data-bs-theme="dark"">
<div class="container">
    <a class="navbar-brand" href="">
        <img src="" class="logo" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:article-list' %}">List articles</a>
            </li>
            {% if user.is_authenticated and user.can_publish %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:article-add' %}">Add article</a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">{{ user.name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:registration' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>